---
- name: Copy disable-ipv6.conf
  copy:
    src: disable-ipv6.conf
    dest: /etc/sysctl.d/disable-ipv6.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload procps service
  when: disable_ipv6 | default(False)
